name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      academia_mongo:
        image: mongo
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.adminCommand('ping')'" --health-interval 10s --health-timeout 5s --health-retries 3
      academia-ollama:
        image: ollama/ollama:latest
        ports:
          - 11434:11434
        options: --health-cmd "curl -f http://localhost:11434 || exit 1" --health-interval 10s --health-timeout 5s --health-retries 3
      academia_server:
        build:
          context: server
          dockerfile: Dockerfile
        ports:
          - 5000:5000
        options: --health-cmd "curl -f http://localhost:5000/health || exit 1" --health-interval 10s --health-timeout 5s --health-retries 3
      academia_client:
        build:
          context: client
          dockerfile: Dockerfile
        ports:
          - 3000:3000
        options: --health-cmd "curl -f http://localhost:3000/health || exit 1" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust this version as per your project

      - name: Install dependencies
        run: |
          cd client && yarn install
          cd ../server && yarn install

      - name: Lint Client
        run: |
          cd client && yarn lint

      - name: Lint Server
        run: |
          cd server && yarn lint

      - name: Run Tests for Server
        run: |
          cd server && yarn test

      - name: Run Tests for Client
        run: |
          cd client && yarn test
