name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js for frontend and backend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies for the backend
      - name: Install Backend Dependencies
        working-directory: ./server
        run: yarn install

      # Lint and Test the backend
      - name: Run Backend Lint
        working-directory: ./server
        run: yarn lint

      - name: Run Backend Tests
        working-directory: ./server
        run: yarn test


  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker images for both frontend and backend
      - name: Build Backend Docker Image
        working-directory: ./server
        run: docker build -t your-backend-image-name .

      - name: Build Frontend Docker Image
        working-directory: ./client
        run: docker build -t your-frontend-image-name .
