name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust this version as per your project

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and Start Services
        run: |
          docker-compose -f docker-compose.yml up --build -d
          
      - name: Wait for services to be ready
        run: |
          until curl -s http://localhost:5000/health; do
            echo "Waiting for server..."
            sleep 5
          done
          until curl -s http://localhost:3000/health; do
            echo "Waiting for client..."
            sleep 5
          done

      - name: Install dependencies for Client and Server
        run: |
          cd client && yarn install
          cd ../server && yarn install

      - name: Lint Client
        run: |
          cd client && yarn lint

      - name: Lint Server
        run: |
          cd server && yarn lint

      - name: Run Tests for Server
        run: |
          cd server && yarn test

      - name: Run Tests for Client
        run: |
          cd client && yarn test

      - name: Tear down Docker Compose
        run: docker-compose down
